- name: put /root/k8s-elasticsearch-config.yaml
  template: src=k8s-elasticsearch-config.yaml dest=/root/k8s-elasticsearch-config.yaml

- name: create /data/pvs
  file: dest=/data/pvs state=directory owner=root mode=0600

- name: put a elasticsearch-pv1.yaml file
  template: src=pv1.yaml dest=/root/elasticsearch-pv1.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ elasticsearch_cluster_namespace }} | grep elasticsearch-data-1
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ elasticsearch_cluster_namespace }} -f /root/elasticsearch-pv1.yaml
  when: result|failed

- name: put a elasticsearch-pv2.yaml file
  template: src=pv2.yaml dest=/root/elasticsearch-pv2.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ elasticsearch_cluster_namespace }} | grep elasticsearch-data-2
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ elasticsearch_cluster_namespace }} -f /root/elasticsearch-pv2.yaml
  when: result|failed

- name: put a elasticsearch-pv3.yaml file
  template: src=pv3.yaml dest=/root/elasticsearch-pv3.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ elasticsearch_cluster_namespace }} | grep elasticsearch-data-3
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ elasticsearch_cluster_namespace }} -f /root/elasticsearch-pv3.yaml
  when: result|failed

- name: put a elasticsearch-pv4.yaml file
  template: src=pv4.yaml dest=/root/elasticsearch-pv4.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ elasticsearch_cluster_namespace }} | grep elasticsearch-data-4
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ elasticsearch_cluster_namespace }} -f /root/elasticsearch-pv4.yaml
  when: result|failed

- name: put a elasticsearch-pv5.yaml file
  template: src=pv5.yaml dest=/root/elasticsearch-pv5.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ elasticsearch_cluster_namespace }} | grep elasticsearch-data-5
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ elasticsearch_cluster_namespace }} -f /root/elasticsearch-pv5.yaml
  when: result|failed

- name: check if a Helm release for elasticsearch-cluster is present
  shell: helm list --namespace={{ elasticsearch_cluster_namespace }} | grep elasticsearch-cluster-release
  register: result
  ignore_errors: true

- name: enable the incubator repo
  shell: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/

- name: install an Elasticsearch cluster using a Helm chart
  shell: helm install -f /root/k8s-elasticsearch-config.yaml incubator/elasticsearch --namespace {{ elasticsearch_cluster_namespace }} --name elasticsearch-cluster-release
  when: result|failed
