- name: enable the incubator repo
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf && helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator

- name: put values
  template: src=values.yml dest=/tmp/elasticsearch-{{ elasticsearch_helm_release }}.yml

- name: upgrade {{ elasticsearch_helm_release }} release using a Helm chart
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf && helm upgrade {{ elasticsearch_helm_release }} incubator/elasticsearch --install --recreate-pods --namespace {{ k8s_namespace }} -f /tmp/elasticsearch-{{ elasticsearch_helm_release }}.yml
