replicas: {{ elasticsearch_data_replicas }}

imageTag: "{{ elasticsearch_image_tag }}"

resources:
  limits:
    cpu: "{{ elasticsearch_data_cpus }}"
  requests:
    cpu: "25m"
    memory: "{{ elasticsearch_data_memory_limit }}"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ storage_class_name }}
  resources:
    requests:
      storage: 1Gi
